### PR TITLE
Measure writing 16 responses, not 1

### PR DESCRIPTION
**Pull request by benaadams**
Web servers will write 16 responses not a single block response (otherwise they aren't testing the infrastructure (e.g. do the writes, encryption coalesce etc)

### CODE REVIEW

**Comment by benaadams** [comment]
Also the two NativeIOCP.cpp files need changing, but it has too many ALL CAPS and _ for my liking 😉

**Comment by benaadams** [comment]
Probably should be more writes; like per header + body; or all headers + body

**Comment by benaadams** [comment]
Main issue here is its testing a single socket api call; e.g. OS: here is a lot of data - that should always be pretty fast - but its not testing the interop cost to the OS of the methods

Also all the tests weren't using same data size; so it makes them all the same.

**Comment by Drawaes** [comment]
I think we know that the internal speed of the encryption function is good, we want to measure the data handling around those calls, as this is what can be changed.

**Comment by geoffkizer** [comment]
As I think I mentioned previously, the point here isn't to measure HTTP performance, the point is to measure raw socket/SSL performance.

Regardless, I'm moving away from using these tests.

**Pull request closed without merging**
